### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by antmorr**
added Linx under IaaS

### CODE REVIEW

**Comment by stn1slv** [comment]
Nice tool, but it's not related to Integration Platform as a Service (iPaaS).

**Comment by antmorr** [comment]
> Nice tool, but it's not related to Integration Platform as a Service (iPaaS).

Thanks - perhaps not a traditional iPaaS but covers all the requirements detailed in the description of an iPaaS

- [iPaaS capabilities](https://www.techtarget.com/searchdatamanagement/feature/Pros-and-cons-of-the-4-best-IPaaS-software-options) include the following:
- ease of use for platform deployment, data integration and app management processes;
- comprehensiveness of integration tool sets and pre-built data connectors;
- level of support for both SaaS and locally hosted applications;
- readiness to support protocols like HTTP, FTP, Open Data Protocol and Advanced Messaging Queuing Protocol;
- flexibility to build custom connectors and modify access mechanisms;
- ability to process, clean and transform data in formats like XML and JSON;
- performance when handling large-scale data operations and concurrent executions;
- support for real-time processing and batch data integration;
- monitoring for failures, latency, resource utilization and workflow performance; and
- security mechanisms for access control, data encryption and single sign-on integrations.


Linx allows users to build simple to complex integrations with ease. It allows you to connect various different services and platforms using APIs, direct database integration, file importing and more. It then allows you to deploy your applications with a single click where it is hosted on a Linx server. This means that the user does not have to worry about hosting, monitoritng or logging. We feel that Linx is the evolution of the integration platform as it allows users not just to create applications that facilitate integration, but to do it with a great amount of flexibility and customization.

**Comment by stn1slv** [comment]
Gartner's description of IPaaS capabilities is more comprehensive than TechTarget's:

- **Application integration features** — that is, the ability for different applications to exchange messages, call other business functions and automate business processes. This integration generally needs to be at the transaction level. It must support use cases such as:

  - Data consistency/synchronization between applications.
  - Composition of new services from aggregations of existing applications or services (typically published as APIs or events).
  - Delivery of a multistep process that touches many systems.
- **Data consistency and sharing features** — that is, the ability for different data stores to synchronize, to move data and to combine, deduplicate and aggregate data from different stores. This integration generally involves a bulk/batch, federated/virtualized or change data capture/replication mode of data delivery. It supports requirements for extracting, transforming, combining and provisioning data to support diverse use cases (such as analytics, data management and integration).
- **B2B ecosystem integration features** — that is, the ability to enable the exchanging of data (such as payments, orders and supply chain information) electronically with business ecosystems and partners by leveraging industry-standard data formats and protocols (such as EDIFACT, X12, Swift, HL7, AS2/AS4). Executing effective B2B processes involves people from nontechnical business roles, along with trading partner onboarding and trading community management. Nontechnical users are provided access to, control over and visibility into the operation of these B2B solutions.
- **API-based integration features** — that is, the ability to create and integrate APIs from different sources and to manage APIs in the context of these integrations.
- **Connectivity features** to support on-premises and cloud-based endpoints, including:
  - Application connectors, such as for Salesforce, Workday, NetSuite, Oracle E-Business Suite and Oracle Fusion Cloud ERP, SAP S/4HANA and SuccessFactors, ServiceNow, Microsoft Dynamics 365 and Marketo.
  - Data source connectors, such as for file systems and SQL and NoSQL databases.
  - Technology connectors, such as for FTP, HTTP, Java Message Service (JMS) and Open Database Connectivity (ODBC).
- **Features to support multiple data and message delivery styles**, including:
  - API-based
  - Messaging/event-based
  - Batch
- **Data and message features** such as validation, mapping and transformation, and routing and orchestration.
- **End-user tools** to develop, test, deploy, execute, administer, monitor and manage integration flows, and to manage the life cycle of the relevant artifacts (transformation maps, routing rules, orchestration flows, adapter configurations and others).

**Comment by antmorr** [comment]
Thanks Stanislav

Linx is a pretty unique tool and covers nearly any backend task (automation, APIs and integration). It can also be used for ETL, data transfer, BPM, API development, microservices and and and....

The reason I added this under iPaaS is that you have listed Mulesoft, which Linx competes with directly.  
It could also be listed under "self-service integration" as the user would need to create (or build) the functionality that they require using prebuilt templates, functions and services.  Most of our customers come from Zapier and IFTTT where thy have 'hit the wall' as the tool cannot handle the complexity of the integration.

Would you consider this?

**Pull request closed without merging**
